"""
POST /ingest — document ingestion endpoint.

Flow: Upload file → Parse → Chunk → Embed (Gemini) → Upsert to vector store.
"""
from __future__ import annotations

import logging
import uuid

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile, status

from api.models import ErrorCode, ErrorResponse, IngestionStatus, IngestionStatusEnum
from api.services.parser import parse_document, SUPPORTED_EXTENSIONS
from api.services.chunker import chunk_document
from api.services.embedder import embed_batch
import api.vectorstore as vectorstore
from api.dependencies import verify_internal_key

logger = logging.getLogger(__name__)
router = APIRouter()


@router.post(
    "/ingest",
    response_model=IngestionStatus,
    status_code=status.HTTP_200_OK,
    summary="Ingest a document",
)
async def ingest_document(
    file: UploadFile = File(..., description="PDF, DOCX, or TXT file"),
    doc_id: str = Form(..., description="UUID generated by Next.js"),
    namespace: str = Form(..., description="Pinecone namespace (user/session ID)"),
    source_file: str = Form(default="", description="Original filename for citations"),
    _: None = Depends(verify_internal_key),
):
    """
    Ingest a document: parse → chunk → embed → upsert to vector store.
    Processing is synchronous for MVP.
    """
    display_name = source_file or file.filename or "unknown"

    # --- Read file bytes ---
    try:
        file_bytes = await file.read()
    except Exception as e:
        logger.error("Failed to read uploaded file: %s", e)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"error": "Failed to read file.", "code": ErrorCode.PARSE_FAILURE},
        )

    # --- Parse ---
    try:
        pages = parse_document(file_bytes, file.content_type or "", display_name)
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"error": str(e), "code": ErrorCode.UNSUPPORTED_FORMAT},
        )
    except Exception as e:
        logger.error("Unexpected parse error for doc_id=%s: %s", doc_id, e)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={"error": "Document parsing failed.", "code": ErrorCode.PARSE_FAILURE},
        )

    # --- Chunk ---
    chunks = chunk_document(pages, doc_id=doc_id, source_file=display_name)
    if not chunks:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"error": "Document produced no chunks.", "code": ErrorCode.PARSE_FAILURE},
        )

    # --- Embed (batch with retry) ---
    try:
        texts = [c.text for c in chunks]
        embeddings = await embed_batch(texts)
        for chunk, emb in zip(chunks, embeddings):
            chunk.embedding = emb
    except Exception as e:
        logger.error("Embedding failed for doc_id=%s: %s", doc_id, e)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error": "Embedding service unavailable after 3 retries.",
                "code": ErrorCode.EMBEDDING_FAILURE,
            },
        )

    # --- Upsert to vector store ---
    try:
        vectors_upserted = vectorstore.upsert_chunks(chunks, namespace=namespace)
    except Exception as e:
        logger.error("Vector store upsert failed for doc_id=%s: %s", doc_id, e)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={"error": "Vector store write failed.", "code": ErrorCode.VECTORSTORE_ERROR},
        )

    logger.info(
        "Ingestion complete: doc_id=%s chunks=%d vectors=%d namespace=%s",
        doc_id,
        len(chunks),
        vectors_upserted,
        namespace,
    )

    return IngestionStatus(
        doc_id=doc_id,
        status=IngestionStatusEnum.complete,
        chunks_created=len(chunks),
        error=None,
    )
